/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'work-items': WorkItem;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'work-items': WorkItemsSelect<false> | WorkItemsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    home: Home;
    about: About;
    work: Work;
    writing: Writing;
    contact: Contact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    writing: WritingSelect<false> | WritingSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Companies, ventures, projects and involvements shown on /work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-items".
 */
export interface WorkItem {
  id: number;
  name: string;
  /**
   * The URL, e.g. /work/signet. Generated from the name if left blank.
   */
  slug?: string | null;
  /**
   * Shown on the card and at the top of the page. Landscape (16:9).
   */
  coverImage?: (number | null) | Media;
  /**
   * Drives which filter the entry appears under.
   */
  type: 'company' | 'venture' | 'project' | 'involvement';
  /**
   * e.g. Founder, Partner, Director, Advisor.
   */
  role?: string | null;
  /**
   * One or two lines, shown on the card and under the heading.
   */
  description?: string | null;
  /**
   * The write-up: what it is, what they do, what you have done for it. Written as an article rather than a formal case study.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional images shown below the write-up.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Their website. Optional.
   */
  url?: string | null;
  /**
   * e.g. 2024, or 2021 to 2023.
   */
  year?: string | null;
  /**
   * Optional pill on the card. Leave blank to show nothing.
   */
  status?: ('active' | 'building' | 'exited') | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'work-items';
        value: number | WorkItem;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-items_select".
 */
export interface WorkItemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  coverImage?: T;
  type?: T;
  role?: T;
  description?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  url?: T;
  year?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identity, social links, footer and default SEO — shared by every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Avatar shown on the home page (a square image works best).
   */
  profileImage?: (number | null) | Media;
  /**
   * Your name — the main heading and the nav wordmark.
   */
  name: string;
  /**
   * Shown under your intro on the home page and again on the contact page.
   */
  socials?:
    | {
        platform:
          | 'instagram'
          | 'x'
          | 'youtube'
          | 'linkedin'
          | 'tiktok'
          | 'threads'
          | 'github'
          | 'facebook'
          | 'email'
          | 'website';
        /**
         * Use a mailto: link for Email.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small text shown in the footer of every page.
   */
  footerText?: string | null;
  /**
   * Appended to each page title, e.g. "About · Benjamin Rutter". Leave blank for none.
   */
  metaTitleSuffix?: string | null;
  /**
   * Used on any page that has not set its own description.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Appended to each page’s own keywords.
   */
  keywords?: string | null;
  /**
   * Used in the Person structured data that search engines read.
   */
  jobTitle?: string | null;
  /**
   * Used on any page that has not set its own (recommended 1200×630).
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The landing page. Name, avatar and socials live in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * The one line under your name. Lead with the intersection.
   */
  bio: string;
  /**
   * A short paragraph under the intro. Keep it to two or three lines.
   */
  statement?: string | null;
  /**
   * The clear next step. Keep this to a handful, the nav already covers the rest.
   */
  links?:
    | {
        /**
         * Optional image across the top of the panel. Landscape (16:9).
         */
        image?: (number | null) | Media;
        title: string;
        /**
         * Two or three lines. Give it enough to be worth clicking.
         */
        description?: string | null;
        /**
         * Small pills along the bottom. Keep to three or four.
         */
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * An external URL, or an internal path such as /work.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Browser tab title and search/social title for this page.
   */
  metaTitle?: string | null;
  /**
   * Short summary for search engines and link previews. Aim for 150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Falls back to the site-wide list. Note that Google ignores the keywords meta tag; this mainly helps other crawlers and keeps the intended terms on record.
   */
  keywords?: string | null;
  /**
   * Image shown when this page is shared (recommended 1200×630). Falls back to the site-wide one.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heading: string;
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional image shown alongside the bio.
   */
  portrait?: (number | null) | Media;
  /**
   * Kept deliberately light. Position by proof, not by title. Expand into its own page only when advisory work is real.
   */
  helpWith?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional short label/value pairs shown as a small grid, e.g. "Based / Dubai".
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Browser tab title and search/social title for this page.
   */
  metaTitle?: string | null;
  /**
   * Short summary for search engines and link previews. Aim for 150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Falls back to the site-wide list. Note that Google ignores the keywords meta tag; this mainly helps other crawlers and keeps the intended terms on record.
   */
  keywords?: string | null;
  /**
   * Image shown when this page is shared (recommended 1200×630). Falls back to the site-wide one.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /work page. Senso and selected proof, linking out to the studio site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: number;
  heading: string;
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  studioUrl?: string | null;
  studioLinkLabel?: string | null;
  /**
   * Sits below the work, so the proof comes first. Keep it understated until advisory work is a bigger part of the picture.
   */
  advisory?: {
    enabled?: boolean | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Browser tab title and search/social title for this page.
   */
  metaTitle?: string | null;
  /**
   * Short summary for search engines and link previews. Aim for 150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Falls back to the site-wide list. Note that Google ignores the keywords meta tag; this mainly helps other crawlers and keeps the intended terms on record.
   */
  keywords?: string | null;
  /**
   * Image shown when this page is shared (recommended 1200×630). Falls back to the site-wide one.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /writing page. Posts are pulled automatically from beehiiv.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writing".
 */
export interface Writing {
  id: number;
  heading: string;
  /**
   * One or two lines directly under the heading.
   */
  intro?: string | null;
  showSubscribe?: boolean | null;
  subscribeHeading?: string | null;
  subscribeBlurb?: string | null;
  postLimit?: number | null;
  /**
   * Browser tab title and search/social title for this page.
   */
  metaTitle?: string | null;
  /**
   * Short summary for search engines and link previews. Aim for 150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Falls back to the site-wide list. Note that Google ignores the keywords meta tag; this mainly helps other crawlers and keeps the intended terms on record.
   */
  keywords?: string | null;
  /**
   * Image shown when this page is shared (recommended 1200×630). Falls back to the site-wide one.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: string;
  /**
   * A short line about what to get in touch about.
   */
  intro?: string | null;
  /**
   * Messages are stored in the CMS under Messages.
   */
  showForm?: boolean | null;
  formHeading?: string | null;
  /**
   * Rendered as a mailto: link. Just the address, no "mailto:" prefix.
   */
  email?: string | null;
  /**
   * Optional, e.g. "Open to advisory roles from Q1".
   */
  availability?: string | null;
  /**
   * Repeats the socials from Site Settings on this page.
   */
  showSocials?: boolean | null;
  /**
   * Browser tab title and search/social title for this page.
   */
  metaTitle?: string | null;
  /**
   * Short summary for search engines and link previews. Aim for 150-160 characters.
   */
  metaDescription?: string | null;
  /**
   * Comma separated. Falls back to the site-wide list. Note that Google ignores the keywords meta tag; this mainly helps other crawlers and keeps the intended terms on record.
   */
  keywords?: string | null;
  /**
   * Image shown when this page is shared (recommended 1200×630). Falls back to the site-wide one.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  profileImage?: T;
  name?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  metaTitleSuffix?: T;
  metaDescription?: T;
  keywords?: T;
  jobTitle?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  bio?: T;
  statement?: T;
  links?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  body?: T;
  portrait?: T;
  helpWith?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  body?: T;
  studioUrl?: T;
  studioLinkLabel?: T;
  advisory?:
    | T
    | {
        enabled?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaUrl?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writing_select".
 */
export interface WritingSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  showSubscribe?: T;
  subscribeHeading?: T;
  subscribeBlurb?: T;
  postLimit?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  showForm?: T;
  formHeading?: T;
  email?: T;
  availability?: T;
  showSocials?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}